### PR TITLE
Add libssl-dev & liblz4-tool

### PR DESCRIPTION
**Pull request by utzcoz**
Google devices and Kernel need this library.

### CODE REVIEW

**Comment by utzcoz** [comment]
cc @pdsouza

**Comment by pdsouza** [comment]
@utzcoz Shall we add kernel deps to the base image? https://github.com/pdsouza/maruos-docker/blob/maru-0.7/Dockerfile#L40

**Comment by utzcoz** [comment]
No problem. I will update it this night. Let's suspend this PR now.

**Comment by utzcoz** [comment]
Sent to https://github.com/pdsouza/maruos-docker/pull/2.

**Comment by utzcoz** [comment]
@pdsouza Maybe set the maru-0.7 branch as the default branch?

**Comment by pdsouza** [comment]
@utzcoz done!

**Pull request closed without merging**
